name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1.5", "luajit-2.1.0-beta3"]
        # luaVersion: ["5.1.5", "5.2.4", "5.3.5", "5.4.1", "luajit-2.0.5", "luajit-2.1.0-beta3", "luajit-openresty", "5.1", "5.4"]
        # machineTag: ["windows-latest", "ubuntu-latest", "macos-latest"]
        machineTag: ["windows-latest"]

    runs-on: ${{ matrix.machineTag }}

    steps:
    - uses: actions/checkout@main

    - name: Build Lua
      uses: './'
      with:
        luaVersion: ${{ matrix.luaVersion }}
        buildCache: false

    - name: Test Lua
      run: lua -e 'print("hi from lua")'
